### PR TITLE
Added support for Import Transactions REST API.

### PR DESCRIPTION
**Pull request by mexzar**
Added support for the Import Transaction POST API.

### CODE REVIEW

**Comment by websmartcentral** [comment]
I guess this comes from here 
https://api.ynab.com/v1#/Transactions/importTransactions

**Comment by mexzar** [comment]
Correct!

**Review by websmartcentral — APPROVED** [review]
i was going to submit a pull request for the URL change as it was a cause of issue for me
the import function is fine - but i can't test it as being in australia i have no bank importable accounts

**Comment by jsmarble** [comment]
Thanks for this!

**Pull request merged**
